features:
  categorical_features: [
        "workclass",
        "education",
        "marital_status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "native_country",
    ]
  continious_features: [
                  'age',
                  'fnlgt',
                  'hours_per_week'
                  ]
